#tweets1 = as.data.frame(tweets_set1)
#tweets2 = as.data.frame(tweets_set2)
#tweets3 = as.data.frame(tweets_set3)

#half = rbind(tweets1, tweets2)
#all = rbind(half, tweets3)

library(tidyverse)
library(rtweet)


df = as.data.frame(sb_tweets_all)

saveRDS(s1, "stringr1.rds")
saveRDS(w1, "words1.rds")
saveRDS(SuperBowlLive_Simple, "sb_simple.rds")
saveRDS(stopwords,"stopwords.rds")
saveRDS(auto, "auto.rds")
saveRDS(cellular, "cellular.rds")
saveRDS(clothing, "clothing.rds")
saveRDS(df1, "df1.rds")
saveRDS(electronics, "electronics.rds")
saveRDS(financial, "financial.rds")
saveRDS(food, "food.rds")
saveRDS(gaming, "gaming.rds")
saveRDS(home, "home.rds")
saveRDS(lifestyle, "lifestyle.rds")
saveRDS(live, "live.rds")
saveRDS(live2, "live2.rds")
saveRDS(media, "media.rds")
saveRDS(movie, "movie.rds")
saveRDS(news, "news.rds")
saveRDS(sports,"sports.rds")
saveRDS(travel, "travel.rds")
saveRDS(tv, "tv.rds")
saveRDS(sb_tweets_1, "sb_tweets_1")
saveRDS(sb_tweets_2, "sb_tweets_2")
saveRDS(sb_tweets_3, "sb_tweets_3")
saveRDS(sb_tweets_all, "sb_tweets_all")
saveRDS(sb_tweets_half, "sb_tweets_half")
